#include "common.h"

/* TODO: Should this sort of data be left as assets? Or auto-generated via script? Or is this okay?
 */

s8 gCharacterNames[35][7] = {
    "",     "Ash",   "Clint", "Diego",  "Eleni",  "Huxley", "Kira",   "Grog", "Dolan",
    "Amon", "Sara",  "Zohar", "Darius", "Zoot",   "",       "Hassan", "",     "Magnus",
    "",     "Lando", "Dumas", "Kane",   "Dallas", "Kurtz",  "Sabina", "",     "",
    "",     "",      "Dolf",  "Leena",  "Clive",  "",       "",       "Kira",
};

s8 gUnitTypeNames[86][11] = {
    "",           "Hero",       "Champion",   "Paragon",    "Soldier",    "Swordsman",
    "Duelist",    "Guardsman",  "Dragoon",    "Archer",     "Bowman",     "Sniper",
    "Hawknight",  "Sky Lord",   "Mage",       "Sorcerer",   "Enchanter",  "Monk",
    "Ninja",      "Healer",     "Bishop",     "Archbishop", "Thief Lord", "Brigand",
    "Hunter",     "HunterImp",  "War Ghost",  "Clay Golem", "Hell Bat",   "Death Ant",
    "Ant arm",    "MadCaptain", "EvilStatue", "Villager",   "MadSoldier", "Guarddog",
    "ShooterImp", "Dark Golem", "BloodGhost", "Dark Lord",  "Sparkie",    "Centurion",
    "Grenadier",  "Blood Bat",  "Deacon",     "Hitman",     "C. Archer",  "Juggernaut",
    "Mimic",      "Jailmaster", "Assassin",   "GreatArmor", "War Master", "Valkyrie",
    "C. Shooter", "C. Knight",  "C. Hawk",    "Bugaboo",    "Wight",      "Skeleton",
    "Eggworm",    "Gold Golem", "Acid Ghost", "DeathAngel", "C. Warlock", "C. Priest",
    "Salamander", "Guardian",   "Basilisk",   "Blk Knight", "Xeno",       "HellKnight",
    "Bahamut",    "Dark Mage",  "Doom Lord",  "Dark Angel", "Mage Tower", "Death Dev.",
    "Vandalier",  "NPC",        "Buccaneer",  "Corsair",    "Warlock",    "C. Armor",
    "Mega Guard", "M. Cannon",
};

s8 gItemNames[139][13] = {
    "",
    "Herb",
    "Megaherb",
    "Mage Oil",
    "Mage Gem",
    "Elixir",
    "Holy H2O",
    "Life Orb",
    "Fire Gem",
    "MoodRing",
    "Aura Gem",
    "WyrmFang",
    "S.sword",
    "L.sword",
    "I.sword",
    "G.sword",
    "M.sword",
    "Caliburn",
    "V.Heart",
    "H.bow",
    "L.bow",
    "Iron bow",
    "Stl.bow",
    "Kill bow",
    "Grt.bow",
    "Rune bow",
    "Staff",
    "L.staff",
    "I.staff",
    "M.staff",
    "S.staff",
    "Arkstaff",
    "Runewand",
    "Iron axe",
    "Battleax",
    "Bloodaxe",
    "Grt.Axe",
    "Ragnarok",
    "I.spear",
    "S.lance",
    "Halberd",
    "D.Spear",
    "Ironclaw",
    "Stl claw",
    "P.claws",
    "D.claws",
    "LthrHelm",
    "LghtHelm",
    "I.helm",
    "Stl mask",
    "Grimhelm",
    "DrgnHelm",
    "Bandanna",
    "L.band",
    "Iron Cap",
    "Stl band",
    "L.mask",
    "R.Crown",
    "Leather",
    "PLeather",
    "Chain",
    "Scale",
    "Plate",
    "Kevlar",
    "Cape",
    "WoolRobe",
    "MstrRobe",
    "MystRobe",
    "Zen Robe",
    "MojoRobe",
    "Nova Key",
    "Earth K.",
    "Mana Key",
    "Chaos K.",
    "Logos K.",
    "Heaven K",
    "Nova P.",
    "Ice P.",
    "Mana P.",
    "chaos P.",
    "Logo P. ",
    "Heaven P",
    "V.Helm",
    "V.Armor",
    "V HEART",
    "Goldcoin",
    "Mithril",
    "Gold Axe",
    "Mad Book",
    "Mushroom",
    "Moon Pie",
    "IronBoot",
    "Unicorn",
    "Kingfoil",
    "HelStone",
    "ShivBook",
    "Ncklace",
    "Banana",
    "Macroman",
    "Tarot",
    "Ramen",
    "Thief Sword",
    "Thief Helm",
    "Thief Mail",
    "Imp Pants",
    "Large Spear",
    "Captain Suit",
    "Red Bandanna",
    "Pirate Suit",
    "Farm Tool",
    "Clothes",
    "Dark Helm",
    "Mad Armor",
    "Death Mask",
    "Lord Armor",
    "Empire Helm",
    "Empire Mail",
    "Bomb",
    "Empire Hood",
    "Empire Robe",
    "Command Helm",
    "CommandArmor",
    "Crimson Band",
    "Crimson Mail",
    "Guard Helm",
    "Guard Mail",
    "Vorpal Chain",
    "Command Helm",
    "Crimson Hood",
    "Crimson Cape",
    "Black Helm",
    "Black Armor",
    "R.Crown",
    "Doom Sword",
    "Doom Crown",
    "Doom Mail",
    "Saint Buster",
    "Holy Helm",
    "Valhala Mail",
};
