#include "common.h"
#include "glyphs.h"

u8 gGlyphStripGroup_800f0b84[14] = {0x1, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6,
                                    0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0x0};

u8 gGlyphStripGroup_800f0b94[7] = {0x1, 0x51, 0x4b, 0x4c, 0x4c, 0x56, 0x0};

u8 gGlyphStripGroup_800f0b9c[5] = {0x1, 0x4d, 0x4e, 0x4f, 0x0};

u8 gGlyphStripGroup_800f0ba4[3] = {0x1, 0x50, 0x0};

u8 gGlyphStripGroup_800f0ba8[7] = {0x1, 0x51, 0x52, 0x53, 0x54, 0x56, 0x0};

u8 gGlyphStripGroup_800f0bb0[7] = {0x1, 0x51, 0x57, 0x58, 0x59, 0x56, 0x0};

u8 gGlyphStripGroup_800f0bb8[8] = {0x1, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x0};

u8 gGlyphStripGroup_800f0bc0[18] = {0x1,  0x5a, 0x65, 0x66, 0x67, 0x68, 0x5c, 0x5b, 0x5d,
                                    0x5e, 0x5f, 0x60, 0x61, 0x62, 0x63, 0x5b, 0x64, 0x0};

u8 gGlyphStripGroup_800f0bd4[28] = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
                                    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
                                    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};

u8 gGlyphStripGroup_800f0bf0[28] = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
                                    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
                                    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};

u8 *gGlyphStripGroups[65] = {NULL,
                             gGlyphStripGroup_800f0b84,
                             gGlyphStripGroup_800f0bb0,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             gGlyphStripGroup_800f0b94,
                             gGlyphStripGroup_800f0b9c,
                             gGlyphStripGroup_800f0ba4,
                             gGlyphStripGroup_800f0ba8,
                             gGlyphStripGroup_800f0bb0,
                             gGlyphStripGroup_800f0bb8,
                             gGlyphStripGroup_800f0bc0,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             gGlyphStripGroup_800f0bd4,
                             gGlyphStripGroup_800f0bf0,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL,
                             NULL};

u8 gGlyphStrip_01[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_TOP_LEFT,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_02[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_03[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_04[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_05[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_06[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_07[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_08[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_09[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_0A[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_0B[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_0C[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_BOTTOM_LEFT,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_4B[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_4C[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_4D[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_TOP_LEFT,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_4E[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_4F[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_BOTTOM_LEFT,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK,
                       GLYPH_BLANK};
u8 gGlyphStrip_50[] = {GLYPH_BLANK,          GLYPH_CHAR_ALT_0, GLYPH_CHAR_ALT_0, GLYPH_CHAR_ALT_0,
                       GLYPH_CHAR_ALT_SLASH, GLYPH_CHAR_ALT_0, GLYPH_CHAR_ALT_0, GLYPH_CHAR_ALT_0,
                       GLYPH_TERMINATOR,     GLYPH_BLANK,      GLYPH_BLANK,      GLYPH_BLANK};
u8 gGlyphStrip_51[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_TOP_LEFT,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_52[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_53[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_54[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_UPPERCASE_H,
                       GLYPH_CHAR_UPPERCASE_P,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_SLASH,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_55[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_PERCENT,
                       GLYPH_BG,
                       GLYPH_CHAR_EXP_1,
                       GLYPH_CHAR_EXP_2,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_SLASH,
                       GLYPH_CHAR_1,
                       GLYPH_CHAR_0,
                       GLYPH_CHAR_0,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_56[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_BOTTOM_LEFT,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_57[] = {GLYPH_BG,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_58[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};
u8 gGlyphStrip_59[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_PERCENT,
                       GLYPH_BG,
                       GLYPH_CHAR_UPPERCASE_H,
                       GLYPH_CHAR_UPPERCASE_P,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_SLASH,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR};

u8 gGlyphStrip_5A[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_TOP_LEFT,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP,
                       GLYPH_CROSSED_BORDER_TOP_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK};
u8 gGlyphStrip_5B[] = {GLYPH_BLANK,      GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR, GLYPH_BLANK};
u8 gGlyphStrip_5C[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_UPPERCASE_L,
                       GLYPH_CHAR_UPPERCASE_E,
                       GLYPH_CHAR_UPPERCASE_V,
                       GLYPH_CHAR_UPPERCASE_E,
                       GLYPH_CHAR_UPPERCASE_L,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK};
u8 gGlyphStrip_5D[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_CHAR_UPPERCASE_H,
                       GLYPH_CHAR_UPPERCASE_P,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_SLASH,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_EQUIP_1,
                       GLYPH_EQUIP_2,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK};
u8 gGlyphStrip_5E[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_CHAR_UPPERCASE_M,
                       GLYPH_CHAR_UPPERCASE_P,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CHAR_SLASH,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK};
u8 gGlyphStrip_5F[] = {GLYPH_BLANK,      GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,         GLYPH_CHAR_EXP_1,
                       GLYPH_CHAR_EXP_2, GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_WEAPON,     GLYPH_CHAR_COLON,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR, GLYPH_BLANK};
u8 gGlyphStrip_60[] = {GLYPH_BLANK,       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,          GLYPH_CHAR_NEXT_1,
                       GLYPH_CHAR_NEXT_2, GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_BG,
                       GLYPH_BG,          GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,  GLYPH_BLANK};
u8 gGlyphStrip_61[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_CHAR_UPPERCASE_A,
                       GLYPH_CHAR_UPPERCASE_T,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_HELMET,
                       GLYPH_CHAR_COLON,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK};
u8 gGlyphStrip_62[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,
                       GLYPH_CHAR_UPPERCASE_D,
                       GLYPH_CHAR_UPPERCASE_F,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_BG,
                       GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK};
u8 gGlyphStrip_63[] = {GLYPH_BLANK,      GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,         GLYPH_CHAR_AGL_1,
                       GLYPH_CHAR_AGL_2, GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_ARMOR,      GLYPH_CHAR_COLON,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR, GLYPH_BLANK};
u8 gGlyphStrip_64[] = {GLYPH_BLANK,
                       GLYPH_CROSSED_BORDER_BOTTOM_LEFT,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM,
                       GLYPH_CROSSED_BORDER_BOTTOM_RIGHT,
                       GLYPH_TERMINATOR,
                       GLYPH_BLANK};
u8 gGlyphStrip_65[] = {GLYPH_BLANK,      GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR, GLYPH_BLANK};
u8 gGlyphStrip_66[] = {GLYPH_BLANK,      GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR, GLYPH_BLANK};
u8 gGlyphStrip_67[] = {GLYPH_BG,         GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR, GLYPH_BLANK};
u8 gGlyphStrip_68[] = {GLYPH_BLANK,      GLYPH_CROSSED_BORDER_LEFT,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_BG,
                       GLYPH_BG,         GLYPH_CROSSED_BORDER_RIGHT,
                       GLYPH_TERMINATOR, GLYPH_BLANK};
u8 gGlyphStrip_C8[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_C9[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_CA[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_CB[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_CC[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_CD[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_CE[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_CF[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D0[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D1[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D2[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D3[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D4[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D5[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D6[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};
u8 gGlyphStrip_D7[] = {
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,      GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK,
    GLYPH_BLANK, GLYPH_BLANK, GLYPH_TERMINATOR, GLYPH_BLANK, GLYPH_BLANK, GLYPH_BLANK};

u8 *gGlyphStrips[216] = {
    NULL,           gGlyphStrip_01, gGlyphStrip_02, gGlyphStrip_03, gGlyphStrip_04, gGlyphStrip_05,
    gGlyphStrip_06, gGlyphStrip_07, gGlyphStrip_08, gGlyphStrip_09, gGlyphStrip_0A, gGlyphStrip_0B,
    gGlyphStrip_0C, NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           gGlyphStrip_4B, gGlyphStrip_4C, gGlyphStrip_4D,
    gGlyphStrip_4E, gGlyphStrip_4F, gGlyphStrip_50, gGlyphStrip_51, gGlyphStrip_52, gGlyphStrip_53,
    gGlyphStrip_54, gGlyphStrip_55, gGlyphStrip_56, gGlyphStrip_57, gGlyphStrip_58, gGlyphStrip_59,
    gGlyphStrip_5A, gGlyphStrip_5B, gGlyphStrip_5C, gGlyphStrip_5D, gGlyphStrip_5E, gGlyphStrip_5F,
    gGlyphStrip_60, gGlyphStrip_61, gGlyphStrip_62, gGlyphStrip_63, gGlyphStrip_64, gGlyphStrip_65,
    gGlyphStrip_66, gGlyphStrip_67, gGlyphStrip_68, NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           NULL,           NULL,           NULL,           NULL,
    NULL,           NULL,           gGlyphStrip_C8, gGlyphStrip_C9, gGlyphStrip_CA, gGlyphStrip_CB,
    gGlyphStrip_CC, gGlyphStrip_CD, gGlyphStrip_CE, gGlyphStrip_CF, gGlyphStrip_D0, gGlyphStrip_D1,
    gGlyphStrip_D2, gGlyphStrip_D3, gGlyphStrip_D4, gGlyphStrip_D5, gGlyphStrip_D6, gGlyphStrip_D7};

u8 gClassIconStartingGlyph[9] = {
    GLYPH_CLASS_KNIGHT_1,   GLYPH_CLASS_ARMOR_1, GLYPH_CLASS_MONK_1,   GLYPH_CLASS_ARCHER_1,
    GLYPH_CLASS_AIRMAN_1,   GLYPH_CLASS_MAGE_1,  GLYPH_CLASS_PRIEST_1, 0x6f,
    GLYPH_CLASS_VANDALIER_1};
